<?php

class Database
{
    private static ?Database $instance = null;
    private mysqli $connection;

    private function __construct()
    {
        $config = require __DIR__ . '/../config/database.php';

        try {
            $this->connection = new mysqli(
                $config['host'],
                $config['username'],
                $config['password'],
                $config['database'],
                $config['port']
            );

            $this->connection->set_charset($config['charset']);
        } catch (mysqli_sql_exception $e) {
            die("Database Connection Error: " . $e->getMessage());
        }
    }

    // Get the single Database instance
    public static function getInstance(): Database
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    // Direct access to raw mysqli object if needed
    public function getConnection(): mysqli
    {
        return $this->connection;
    }

    /**
     * Executes a prepared statement securely
     * 
     * @param string $sql The parameterized SQL query
     * @param array $params Array of parameters to bind
     * @return mysqli_stmt
     */
    public function query(string $sql, array $params = []): mysqli_stmt
    {
        $stmt = $this->connection->prepare($sql);

        if (!empty($params)) {
            $types = '';
            foreach ($params as $param) {
                if (is_int($param)) {
                    $types .= 'i';
                } elseif (is_float($param)) {
                    $types .= 'd';
                } elseif (is_string($param)) {
                    $types .= 's';
                } else {
                    $types .= 'b';
                }
            }

            $stmt->bind_param($types, ...$params);
        }

        $stmt->execute();
        return $stmt;
    }

    /**
     * Fetch all matching rows as an associative array
     */
    public function fetchAll(string $sql, array $params = []): array
    {
        $stmt = $this->query($sql, $params);
        $result = $stmt->get_result();
        $rows = $result->fetch_all(MYSQLI_ASSOC);
        $stmt->close();
        return $rows;
    }

    /**
     * Fetch a single row as an associative array
     */
    public function fetchOne(string $sql, array $params = []): ?array
    {
        $stmt = $this->query($sql, $params);
        $result = $stmt->get_result();
        $row = $result->fetch_assoc();
        $stmt->close();
        return $row ?: null;
    }

    /**
     * Get the ID generated by the last INSERT query
     */
    public function lastInsertId(): int
    {
        return (int) $this->connection->insert_id;
    }
}